### PR TITLE
Update route to compiler plug-ins

### LINKED ISSUE #36: Broken path
https://github.com/arrow-kt/arrow-analysis/blob/6e10eacaab5e135d316054fe00009dd3d9565760/analysis/example/build.gradle.kts#L43

### PR DESCRIPTION
**Pull request by serras**
Fixes #36 

Alas, the compiler does *not* run in the `laws` and `example` projects (you can see this by inspecting the JAR created for `laws` and seeing that no `@Pre` or `@Post` annotations are present). Any ideas on how to fix this? @raulraja @i-walker @nomisRev

### CODE REVIEW

**Comment by serras** [comment]
But weirdly it does run in CI :/

**Comment by serras** [comment]
After digging a bit more I'm suspecting that this might be related to the versioning plug-in. In my local system I get weird versions like `2.0.2-SNAPSHOT-<date>+<time>Z`, whereas in CI they are much simpler.

Is there a way to see whether this is the case? Maybe changing some configuration in the versioning plug-in? @i-walker

**Comment by JavierSegoviaCordoba** [comment]
> After digging a bit more I'm suspecting that this might be related to the versioning plug-in. In my local system I get weird versions like `2.0.2-SNAPSHOT-<date>+<time>Z`, whereas in CI they are much simpler.
> 
> 
> 
> Is there a way to see whether this is the case? Maybe changing some configuration in the versioning plug-in? @i-walker 

The date you are getting is because you have something modified in local. If you commit those files you will get a specific version based on the commit hash.

**Comment by serras** [comment]
That means that I can only test the project with a clean Git status?

**Comment by i-walker** [comment]
Yes @serras, that is the case for most arrow projects if you depend on build output

**Comment by JavierSegoviaCordoba** [comment]
I can add a feature to the version plugin to force a hash version even without a clean status so we can test locally without having to commit files.

For example:

`./gradlew -PuseTimestamp=false`

**Comment by serras** [comment]
That would be wonderful :)

**Comment by JavierSegoviaCordoba** [comment]
@serras curiously I had this already implemented and now when I was starting to implement it I saw it was resolved.

The usage is: 

```shell
./gradlew -Psemver.checkClean=false
```

**Comment by serras** [comment]
It worked! @JavierSegoviaCordoba thanks for the hint :)

**Pull request merged**
